#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
#  Custom Debian ISO Configurator
#  Run this first to set your preferences, then run build-iso.sh to compile.
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

CONFIG_FILE="$(dirname "$0")/.build-config"

echo ""
echo "╔══════════════════════════════════════════════╗"
echo "║      Custom Debian ISO Configurator          ║"
echo "╚══════════════════════════════════════════════╝"
echo ""

# ── 1. OS Name ────────────────────────────────────────────────────────────────
echo "Step 1 of 3 — OS Name"
echo "This becomes the distro name shown in grub, login screen, and /etc/os-release."
read -rp "  Enter your OS name [default: Vortex OS]: " OS_NAME
OS_NAME="${OS_NAME:-Vortex OS}"

# Sanitise: lowercase, spaces → dashes, strip special chars
OS_SLUG=$(echo "$OS_NAME" | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | tr -cd '[:alnum:]-')
echo "  → Slug for filenames: ${OS_SLUG}"
echo ""

# ── 2. Wallpaper ──────────────────────────────────────────────────────────────
echo "Step 2 of 3 — Desktop Wallpaper"
echo "Provide a direct URL to a .jpg or .png image (min 1920×1080 recommended)."
echo "Leave blank to use a built-in default wallpaper."
read -rp "  Wallpaper URL: " WALLPAPER_URL
WALLPAPER_URL="${WALLPAPER_URL:-}"
echo ""

# ── 3. Pre-installed Applications ─────────────────────────────────────────────
echo "Step 3 of 3 — Pre-installed Applications"
echo "Choose the apps you want bundled into the ISO."
echo ""
echo "  Available options (enter the numbers, space-separated):"
echo ""
echo "  Browsers"
echo "    1) Firefox ESR         (web browser)"
echo "    2) Chromium            (web browser)"
echo ""
echo "  Productivity"
echo "    3) LibreOffice         (office suite)"
echo "    4) Thunderbird         (email client)"
echo "    5) Gedit               (text editor)"
echo "    6) GIMP                (image editor)"
echo "    7) Inkscape            (vector graphics)"
echo ""
echo "  Media"
echo "    8) VLC                 (media player)"
echo "    9) Rhythmbox           (music player)"
echo "   10) Shotwell            (photo viewer)"
echo ""
echo "  Development"
echo "   11) VSCodium            (code editor)"
echo "   12) Git                 (version control)"
echo "   13) Python 3 + pip      (scripting)"
echo ""
echo "  System / Utilities"
echo "   14) htop                (process monitor)"
echo "   15) Timeshift           (system backup)"
echo "   16) Gparted             (disk manager)"
echo "   17) Network Manager     (already included)"
echo "   18) Mousepad            (lightweight text editor)"
echo ""
echo "  Communication"
echo "   19) Discord             (voice, video & chat)"
echo ""

read -rp "  Your choices [e.g. 1 3 8 14]: " SELECTIONS
echo ""

# Map selections to package names
PACKAGES=()
declare -A PKG_MAP=(
  [1]="firefox-esr"
  [2]="chromium"
  [3]="libreoffice"
  [4]="thunderbird"
  [5]="gedit"
  [6]="gimp"
  [7]="inkscape"
  [8]="vlc"
  [9]="rhythmbox"
  [10]="shotwell"
  [11]="codium"
  [12]="git"
  [13]="python3 python3-pip"
  [14]="htop"
  [15]="timeshift"
  [16]="gparted"
  [18]="mousepad"
  [19]="discord"
)

for num in $SELECTIONS; do
  if [[ -n "${PKG_MAP[$num]:-}" ]]; then
    PACKAGES+=("${PKG_MAP[$num]}")
  else
    echo "  ⚠  Unknown selection '$num' — skipped."
  fi
done

PACKAGES_STR="${PACKAGES[*]:-}"

# ── Summary ───────────────────────────────────────────────────────────────────
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Configuration Summary"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  OS Name    : ${OS_NAME}"
echo "  OS Slug    : ${OS_SLUG}"
echo "  Wallpaper  : ${WALLPAPER_URL:-<default built-in>}"
echo "  Packages   : ${PACKAGES_STR:-<none selected>}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

read -rp "Save this configuration and continue? [Y/n]: " CONFIRM
CONFIRM="${CONFIRM:-Y}"
if [[ ! "$CONFIRM" =~ ^[Yy]$ ]]; then
  echo "Aborted. Nothing was saved."
  exit 0
fi

# ── Write config file ─────────────────────────────────────────────────────────
cat > "$CONFIG_FILE" <<EOF
# Generated by configure.sh on $(date)
OS_NAME="${OS_NAME}"
OS_SLUG="${OS_SLUG}"
WALLPAPER_URL="${WALLPAPER_URL}"
PACKAGES="${PACKAGES_STR}"
EOF

echo ""
echo "✅  Configuration saved to: ${CONFIG_FILE}"
echo ""
echo "Next step:"
echo "  sudo ./build-iso.sh"
echo ""
